image_size: 320
data_dir: "/scratch/gluo/fastMRI/vols"
schedule_sampler: "uniform"
lr: 0.0001
weight_decay: 0.0
lr_anneal_steps: 0
batch_size: 1
microbatch: -1  # -1 disables microbatches
ema_rate: 0.9999  # comma-separated list of EMA values
log_interval: 10
save_interval: 10000
use_fp16: False
fp16_scale_growth: 0.001
in_channels: 2
logdir: '/home/gluo/temporal/logs/fastmri_320_cplx'
learn_sigma: true
attention_resolutions: "20,10"
mag: false
dataset: 'fastmri'
noisy_x0: false
latent: false